#!/bin/bash
#https://github.com/ch604/cpanel-wildcard-autossl
#Distributed under BSD-3 license
#Cronjob script

version=0.1

domain="[[REPLACE]]"

#run certbot command with posthook and cloudflare creds file
# certbot certonly --dns-cloudflare --dns-cloudflare-credentials /root/.cwa-secrets/$domain.ini -d ${domain},*.${domain} --preferred-challenges dns-01
